# Generated by Django 3.2.7 on 2021-11-09 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mission_type', models.CharField(max_length=50)),
                ('launched', models.IntegerField()),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('star_type', models.CharField(max_length=50)),
                ('mass', models.CharField(max_length=50)),
                ('diameter', models.CharField(max_length=50)),
                ('distance', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('missions', models.ManyToManyField(to='main_app.Mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('satellite_type', models.CharField(max_length=50)),
                ('mass', models.CharField(max_length=50)),
                ('diameter', models.CharField(max_length=50)),
                ('distance', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('missions', models.ManyToManyField(to='main_app.Mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('planet_type', models.CharField(max_length=50)),
                ('mass', models.CharField(max_length=50)),
                ('diameter', models.CharField(max_length=50)),
                ('distance', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('missions', models.ManyToManyField(to='main_app.Mission')),
                ('satellite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.satellite')),
                ('star', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.star')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
