# Generated by Django 3.2.8 on 2021-11-09 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='PlanetPhoto',
        ),
        migrations.CreateModel(
            name='StarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.star')),
            ],
        ),
        migrations.CreateModel(
            name='SatellitePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.satellite')),
            ],
        ),
    ]
