# Generated by Django 3.2.7 on 2021-11-09 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211109_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='satellite',
        ),
        migrations.AddField(
            model_name='satellite',
            name='planet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.planet'),
        ),
    ]
