# Generated by Django 3.2.7 on 2021-11-05 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_planet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
