# Generated by Django 3.2.8 on 2021-11-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_satellite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mission_type', models.CharField(max_length=50)),
                ('launched', models.IntegerField()),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='planet',
            name='missions',
            field=models.ManyToManyField(to='main_app.Mission'),
        ),
        migrations.AddField(
            model_name='satellite',
            name='missions',
            field=models.ManyToManyField(to='main_app.Mission'),
        ),
        migrations.AddField(
            model_name='star',
            name='missions',
            field=models.ManyToManyField(to='main_app.Mission'),
        ),
    ]
