# Generated by Django 3.2.8 on 2021-11-08 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20211108_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='planet',
        ),
        migrations.AddField(
            model_name='planet',
            name='star',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.star'),
        ),
    ]
